name: 'Write Application Config'
description: 'Write application config.json file'
author: 'Your Name'

inputs:
  app_config:
    description: 'Application config.json content'
    required: true
  app_config_path:
    description: 'Path where config.json will be created'
    required: false
    default: 'config.json'

runs:
  using: 'composite'
  steps:
    - name: Write config.json
      shell: bash
      run: |
        # Mask the config value to prevent it from appearing in logs
        echo "::add-mask::${{ inputs.app_config }}"

        # Write the config and validate it's valid JSON
        echo '${{ inputs.app_config }}' > "${{ inputs.app_config_path }}"

        # Validate JSON format
        if ! jq empty "${{ inputs.app_config_path }}" 2>/dev/null; then
          echo "::error::APP_CONFIG is not valid JSON"
          exit 1
        fi

        echo "::notice::Application config file created successfully"
